import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import 'firebase_options.dart'; // This file was generated by the FlutterFire CLI

// This function needs to be a top-level function (not inside a class)
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, like Firestore,
  // make sure you call `initializeApp` before using them.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint("Handling a background message: ${message.messageId}");
}

class FirebaseMessagingService {
  // We will use FirebaseMessaging.instance directly in the methods
  // instead of initializing it as a final variable here. This avoids
  // the error because the constructor is now empty and safe to call.

  final FlutterLocalNotificationsPlugin _flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  /// Initializes Firebase and sets up messaging handlers.
  /// This MUST be called from main() after WidgetsFlutterBinding.ensureInitialized().
  Future<void> init() async {
    // This is the required initialization step.
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

    // Now that Firebase is initialized, we can safely use FirebaseMessaging.instance
    await FirebaseMessaging.instance.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );

    // Get the FCM token for this device
    final String? fcmToken = await FirebaseMessaging.instance.getToken();
    debugPrint("========================================");
    debugPrint("FCM Token: $fcmToken");
    debugPrint("========================================");
    // You will need this token to send a test notification from the Firebase console

    // Set up background message handler
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    // Handle foreground messages
    _initForegroundNotifications();
  }

  /// Initializes the local notifications plugin for foreground messages.
  void _initForegroundNotifications() {
    // Android initialization
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');

    // iOS/macOS initialization
    const DarwinInitializationSettings initializationSettingsIOS =
        DarwinInitializationSettings();

    const InitializationSettings initializationSettings = InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );

    _flutterLocalNotificationsPlugin.initialize(initializationSettings);

    // Listen for incoming messages while the app is in the foreground
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      debugPrint('Got a message whilst in the foreground!');
      debugPrint('Message data: ${message.data}');

      if (message.notification != null) {
        debugPrint(
            'Message also contained a notification: ${message.notification}');
        _showLocalNotification(message);
      }
    });
  }

  /// Shows a local notification using the flutter_local_notifications plugin.
  void _showLocalNotification(RemoteMessage message) {
    RemoteNotification? notification = message.notification;
    AndroidNotification? android = message.notification?.android;

    if (notification != null && android != null) {
      _flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        NotificationDetails(
          android: AndroidNotificationDetails(
            'high_importance_channel', // A unique channel ID
            'High Importance Notifications', // A channel name
            channelDescription:
                'This channel is used for important notifications.',
            importance: Importance.max,
            priority: Priority.high,
            icon: android.smallIcon,
          ),
          iOS: const DarwinNotificationDetails(),
        ),
      );
    }
  }

  /// A helper method to get the current FCM token.
  Future<String?> getFcmToken() async {
    // It's safe to call this now because we assume init() has been called from main().
    return await FirebaseMessaging.instance.getToken();
  }
}

