// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbkLOfaH6qTzWLYRmhQaDaIY4oikueBeg',
    appId: '1:1085096157465:web:f8cff4dbabdf759b47e588',
    messagingSenderId: '1085096157465',
    projectId: 'sale-tracking-app-844f3',
    authDomain: 'sale-tracking-app-844f3.firebaseapp.com',
    storageBucket: 'sale-tracking-app-844f3.firebasestorage.app',
    measurementId: 'G-DLT627W5HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkdhbBc5A7XF0dS6ucxO1Vujq8aItKfNg',
    appId: '1:1085096157465:android:498f3b1c76588d5c47e588',
    messagingSenderId: '1085096157465',
    projectId: 'sale-tracking-app-844f3',
    storageBucket: 'sale-tracking-app-844f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOXzAmrNtjXe_re5wIWQ6dJ1Y9DOQhGzk',
    appId: '1:1085096157465:ios:49aea1b9823ab81c47e588',
    messagingSenderId: '1085096157465',
    projectId: 'sale-tracking-app-844f3',
    storageBucket: 'sale-tracking-app-844f3.firebasestorage.app',
    iosBundleId: 'org.VPSsolutions.VPStechllc.VPSTechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOXzAmrNtjXe_re5wIWQ6dJ1Y9DOQhGzk',
    appId: '1:1085096157465:ios:49aea1b9823ab81c47e588',
    messagingSenderId: '1085096157465',
    projectId: 'sale-tracking-app-844f3',
    storageBucket: 'sale-tracking-app-844f3.firebasestorage.app',
    iosBundleId: 'org.VPSsolutions.VPStechllc.VPSTechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbkLOfaH6qTzWLYRmhQaDaIY4oikueBeg',
    appId: '1:1085096157465:web:4067804ff72cf62247e588',
    messagingSenderId: '1085096157465',
    projectId: 'sale-tracking-app-844f3',
    authDomain: 'sale-tracking-app-844f3.firebaseapp.com',
    storageBucket: 'sale-tracking-app-844f3.firebasestorage.app',
    measurementId: 'G-FTJ08BTY6B',
  );
}
